name: "IOS Test"
description: "Sets up Flutter and installs dependencies."
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Run Integration Tests on Android API Level 21
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 21
        cores: 3
        working-directory: example
        target: google_apis
        arch: x86_64
        script: |
          flutter test integration_test/original_package_test.dart;
          flutter test integration_test/path_provider_android_test.dart;
