name: "IOS Test"
description: "Sets up Flutter and installs dependencies."
runs:
  using: "composite"
  steps:
    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v3

    - name: AVD cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.api-level }}

    - name: Generate AVD snapshot for caching.
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 35
        cores: 3
        working-directory: example
        target: google_apis
        arch: x86_64
        force-avd-creation: false
        disable-animations: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: echo "Generated AVD snapshot for caching."

    - name: Run Integration Tests on Android API Level 21
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 35
        cores: 3
        working-directory: example
        target: google_apis
        arch: x86_64
        force-avd-creation: false
        disable-animations: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: |
          flutter test integration_test/original_package_test.dart;
          flutter test integration_test/path_provider_android_test.dart;
