name: "Android Test"
description: "Runs integration tests on Android."
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Run Integration Tests on Android API Level 35
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 35
        cores: 3
        working-directory: example
        target: google_apis
        arch: x86_64
        script: |
          flutter test integration_test/original_package_test.dart;
          flutter test integration_test/path_provider_android_test.dart;
    - name: Run Integration Tests on Android API Level 21
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 21
        cores: 3
        working-directory: example
        target: google_apis
        arch: x86_64
        # On a normal computer, the `path_provider_android_test.dart` test passes.
        # We will skip it here becuase the Emulator on GitHub Actions is not passing
        # it.
        # This test fails for the old package too, so it is not a problem with the new package.
        script: |
          flutter test integration_test/original_package_test.dart;
