name: path_provider_ffi
description: "A Flutter plugin for getting common filesystem paths synchronously using FFI"
version: 2.1.5
homepage: https://github.com/dickermoshe/path_provider_ffi

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  jni: ^0.14.1
  meta: ^1.16.0
  objective_c: ^7.1.0
  path: ^1.9.1
  xdg_directories: ^1.1.0

dev_dependencies:
  jnigen: ^0.14.1

  ffigen: ^18.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.1.8
