name: "IOS Test"
description: "Sets up Flutter and installs dependencies."
runs:
  using: "composite"
  steps:
    - name: List simulators
      shell: bash
      run: "xcrun xctrace list devices"

    - name: Start simulator
      shell: bash
      run: |
        IPHONE=$(xcrun xctrace list devices  2>&1 | grep -m 1 "iPhone" | awk -F'[()]' '{print $4}')
        xcrun simctl boot $IPHONE

    - name: Run Integration Tests
      working-directory: example
      shell: bash
      run: |
        flutter test ./integration_test/original_package_test.dart;
        flutter test ./integration_test/path_provider_foundation_test.dart;
