name: Test Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Run Main Tests
        run: |
          flutter test

      - name: Run Integration Tests
        working-directory: example
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            flutter test .\integration_test\original_package_test.dart -d windows;
            flutter test .\integration_test\path_provider_windows_test.dart -d windows;
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            flutter test ./integration_test/original_package_test.dart -d macos;
            flutter test ./integration_test/path_provider_foundation_test.dart -d macos;
          else
            flutter test ./integration_test/original_package_test.dart -d linux;
            flutter test ./integration_test/path_provider_linux_test.dart -d linux;
          fi
