name: Test Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        android-api-level: [21, 35]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/flutter-setup

      - name: Run Regular Tests
        run: |
          flutter test

      - name: Run Windows Integration Tests
        if: runner.os == 'Windows'
        run: |
          flutter test integration_test/original_package_test.dart -d windows;
          flutter test integration_test/path_provider_windows_test.dart -d windows;
      - name: Run Linux Integration Tests
        if: runner.os == 'Linux'
        run: |
          xvfb-run flutter test ./integration_test/original_package_test.dart -d linux;
          xvfb-run flutter test ./integration_test/path_provider_linux_test.dart -d linux;
      - name: Run MacOS Integration Tests
        if: runner.os == 'macOS'
        run: |
          flutter test ./integration_test/original_package_test.dart -d macos;
          flutter test ./integration_test/path_provider_foundation_test.dart -d macos;
      - name: Run IOS Integration Tests
        if: runner.os == 'macOS'
        uses: ./.github/actions/ios-test
      - name: Run Android Integration Tests
        if: runner.os == 'Linux'
        uses: ./.github/actions/android-test
        with:
          api-level: 30
