# The name of this workflow as it appears in the Actions tab of your repository.
name: CI - Internal PRs Auto-Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       uses: ./.github/actions/flutter-setup

  #     - name: Run Tests
  #       shell: bash
  #       run: flutter test

  # test_windows:
  #   name: Test Windows
  #   runs-on: windows-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       uses: ./.github/actions/flutter-setup

  #     - name: Run Windows Integration Tests
  #       shell: bash
  #       working-directory: example
  #       run: |
  #         flutter test integration_test/original_package_test.dart -d windows;
  #         flutter test integration_test/path_provider_windows_test.dart -d windows;

  # test_linux:
  #   name: Test Linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       uses: ./.github/actions/flutter-setup

  #     - name: Run Linux Integration Tests
  #       shell: bash
  #       working-directory: example
  #       run: |
  #         xvfb-run flutter test ./integration_test/original_package_test.dart -d linux;
  #         xvfb-run flutter test ./integration_test/path_provider_linux_test.dart -d linux;

  # test_macos:
  #   name: Test MacOS
  #   runs-on: macos-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       uses: ./.github/actions/flutter-setup

  #     - name: Run MacOS Integration Tests
  #       shell: bash
  #       working-directory: example
  #       run: |
  #         flutter test ./integration_test/original_package_test.dart -d macos;
  #         flutter test ./integration_test/path_provider_foundation_test.dart -d macos;

  # test_ios:
  #   name: Test IOS
  #   runs-on: macos-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       uses: ./.github/actions/flutter-setup

  #     - name: Run IOS Integration Tests
  #       uses: ./.github/actions/ios-test

  test_android:
    name: Test Android
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/flutter-setup

      - name: Run Android Integration Tests
        shell: bash
        working-directory: example
        run: |
          flutter test ./integration_test/original_package_test.dart -d android;
          flutter test ./integration_test/path_provider_android_test.dart -d android;
